# fly.toml app configuration file generated for mue-api on 2024-09-02T02:12:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mue-api'
primary_region = 'cdg'

[build]
  build-target = "runner"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
