account_id = "950e96e5beb222c4eeb9962512a6d6fc"
name = "api"
main = "src/index.js"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]
upload_source_maps = true
workers_dev = true
routes = [
	{ pattern = "api.muetab.com", custom_domain = true, zone_name = "muetab.com" },
	{ pattern = "marketplace.muetab.com", custom_domain = true, zone_name = "muetab.com" }
]
kv_namespaces = [
  { binding = "cache", id = "08c0008096b7486a9532c5be43e48a7f" }
]

[[services]]
  binding = "WEBSTORES"
  service = "webstores-api"

[vars]
  UNSPLASH_REFERRAL = "mue"
  PEXELS_COLLECTION = "iwf78dt"
  SPONSORS_NAME = "mue"

# SECRETS:
# 	SUPABASE_URL
# 	SUPABASE_TOKEN
# 	UNSPLASH_TOKEN
# 	PEXELS_TOKEN
# 	MAPBOX_TOKEN
# 	OPENWEATHER_TOKEN
