account_id = "950e96e5beb222c4eeb9962512a6d6fc"
name = "api"
main = "src/index.js"
compatibility_date = "2026-02-24"
compatibility_flags = [ ]
upload_source_maps = true
workers_dev = true
routes = [
	{ pattern = "api.muetab.com", custom_domain = true, zone_name = "muetab.com" },
	{ pattern = "marketplace.muetab.com", custom_domain = true, zone_name = "muetab.com" }
]
kv_namespaces = [
  { binding = "cache", id = "08c0008096b7486a9532c5be43e48a7f" }
]

[[d1_databases]]
  binding = "DB"
  database_name = "mue-content"
  database_id = "5b6376e6-1d2a-4f3b-b463-0d6a1b387be1"

[placement]
mode = "smart"

[alias]
"@/" = "./src/"

[vars]
  UNSPLASH_REFERRAL = "mue"
  PEXELS_COLLECTION = "iwf78dt"
  SPONSORS_NAME = "mue"

# SECRETS:
# 	UNSPLASH_TOKEN
# 	PEXELS_TOKEN
# 	MAPBOX_TOKEN
# 	OPENWEATHER_TOKEN

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1